# Generated by Django 4.1 on 2022-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="perform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(max_length=700)),
                ("image", models.ImageField(upload_to="about/")),
            ],
        ),
    ]
