# Generated by Django 4.1 on 2022-11-15 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_perform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
