# Generated by Django 4.1 on 2023-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel_info",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel_info",
            name="banner",
            field=models.ImageField(null=True, upload_to="hotel/"),
        ),
        migrations.AlterField(
            model_name="hotel_info",
            name="hotel_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
