# Generated by Django 4.1 on 2022-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="password",
            field=models.CharField(default="DEFAULT VALUE", max_length=50),
        ),
    ]
