# Generated by Django 4.1 on 2022-12-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hotel", "0003_alter_owner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
