# Generated by Django 4.1 on 2022-11-15 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("QuranHadith", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hadith",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
